//user
export const TOKEN = 'TOKEN';
export const SET_USER = 'SET_USER';
export const SET_IS_SIGNIN = 'SET_IS_SIGNIN';
export const SET_TOGGLE_MODAL = 'SET_TOGGLE_MODAL';
export const SET_NAME = 'SET_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_DOB = 'SET_DOB';
export const SET_ANNIVERSARY_DATE = 'SET_ANNIVERSARY_DATE';
export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER';
export const CLEAR_SESSION = 'CLEAR_SESSION';

export const FAVORATES = 'FAVORATES';
export const CUISINEPREFERENCE = 'CUISINEPREFERENCE';
export const PROFILEIMAGE = 'PROFILEIMAGE';
export const GUEST_ID = 'GUEST_ID';

//Merchant

export const SET_MERCHANT_NAME = 'SET_MERCHANT_NAME';
export const SET_MERCHANT_ADDRESS = 'SET_MERCHANT_ADDRESS';
export const SET_MERCHANT_STATE = 'SET_MERCHANT_STATE';
export const SET_MERCHANT_CITY = 'SET_MERCHANT_CITY';
export const SET_MERCHANT_ZIP = 'SET_MERCHANT_ZIP';
export const SET_MERCHANT_IMAGE = 'SET_MERCHANT_IMAGE';
export const SET_MERCHANT_ABOUT = 'SET_MERCHANT_ABOUT';
export const SET_MERCHANT_PARKING_SLOT = 'SET_MERCHANT_PARKING_SLOT';
